    {{ 
        SELECT {ent} (COUNT({val}) AS {val_count}) WHERE
        {{
            {triples}
            {ent} {relation} {val}.
        }}
        GROUP BY {ent}
    }}
    FILTER({val_count} {comparator} {literal})
